---
- hosts: server
  tasks:
    - name: Provision EC2 instance
      ec2:
        Key_name: AnsibleEC2
        region: ap-south-1
        instance_type: t2.micro
        image: ami-0614680123427b75e
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: AWS-Ansible
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 8
        monitoring: yes
        vpc_subnet_id: subnet-096f3fc0c9a4cde89
        assign_public_ip: yes
        group: AnsibleEC2
      register: ec2
